import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { SecretSantaOwnerList } from "../../components/SecretSantaOwnerList";

import { NavBar } from "../../components/NavBar";

import { api } from "../../utils/api";

const SantaList: NextPage = () => {
  return (
    <>
      <Head>
        <title>Super Secret Santa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-700 text-white">
        <div className="justify-top container mt-16 bg-gray-600 py-16 px-10 shadow-lg">
          <h1 className="text-5xl font-bold text-white">
            Upcoming Events you're organising
          </h1>
          <SecretSantaOwnerList />

          <Link href="/santa/create">
            <button className="inline-flex items-center justify-center gap-2 rounded-md border border-transparent bg-blue-500 py-3 px-4 text-sm font-semibold text-white transition-all hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 dark:focus:ring-offset-gray-800">
              Create a new Event!
            </button>
          </Link>
        </div>
      </main>
    </>
  );
};

export default SantaList;
