import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { NavBar } from "../../components/NavBar";

import { api } from "../../utils/api";

const SantaList: NextPage = () => {
  const secretSantas = api.secretSanta.getAllSecretSantasByUser.useQuery();
  return (
    <>
      <Head>
        <title>Super Secret Santa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-700 text-white">
        <div className="justify-top container mt-16 bg-gray-600 py-16 px-10 shadow-lg">
          <h1 className="text-5xl font-bold text-white">
            Upcoming Events you're organising
          </h1>
          {secretSantas && (
            <span>
              {secretSantas.data?.map((ss) => {
                return (
                  <Link href={`/santa/${ss.id}`}>
                    <div className="my-10 bg-gray-500 p-10">
                      <h2 className="text-2xl font-bold">{ss.name}</h2>
                      <p className="text-xl">
                        {ss.participants.length ? ss.participants.length : 0}{" "}
                        members
                      </p>
                    </div>
                  </Link>
                );
              })}
            </span>
          )}

          <Link href="/santa/create">Create a Secret Santa</Link>
        </div>
      </main>
    </>
  );
};

export default SantaList;
