import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { SecretSantaOwnerList } from "../../components/SecretSantaOwnerList";

import { NavBar } from "../../components/NavBar";

import { api } from "../../utils/api";

const SantaList: NextPage = () => {
  const secretSantas = api.secretSanta.getAllSecretSantasByUser.useQuery();
  return (
    <>
      <Head>
        <title>Super Secret Santa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-700 text-white">
        <div className="justify-top container mt-16 bg-gray-600 py-16 px-10 shadow-lg">
          <h1 className="text-5xl font-bold text-white">
            Upcoming Events you're organising
          </h1>
          <SecretSantaOwnerList />

          <Link href="/santa/create">Create a Secret Santa</Link>
        </div>
      </main>
    </>
  );
};

export default SantaList;
