import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { NavBar } from "../components/NavBar";

import { api } from "../utils/api";
import { Footer } from "../components/Footer";

const ConnectDone: NextPage = () => {
  return (
    <>
      <Head>
        <title>Super Secret Santa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <html className="h-full">
        <body className="flex h-full">
          <div className="mx-auto flex h-full w-full max-w-[60rem] flex-col">
            <header className="z-50 mb-auto flex w-full justify-center py-4">
              <nav className="px-4 sm:px-6 lg:px-8" aria-label="Global">
                <a
                  className="flex-none text-xl font-semibold dark:text-white sm:text-3xl"
                  href="/"
                  aria-label="Brand"
                >
                  Super Secret Santa
                </a>
              </nav>
            </header>

            <div className="py-10 px-4 text-center sm:px-6 lg:px-8">
              <h1 className="block text-7xl font-bold text-gray-800 dark:text-white sm:text-9xl">
                You're all set!
              </h1>
              <h1 className="block text-2xl font-bold text-white"></h1>
              <p className="mt-3 text-gray-600 dark:text-gray-400">
                You've connected your account to this event. Now just wait for
                the drawing to happen!
              </p>
            </div>

            <Footer />
          </div>
        </body>
      </html>
    </>
  );
};

export default ConnectDone;
