import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { NavBar } from "../components/NavBar";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Super Secret Santa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-br from-[#00B32C] to-[#DC3D2A] text-gray-600">
        <div className="container flex flex-col items-center justify-center gap-12 bg-gray-600 px-4 py-16 text-white shadow-lg">
          <h1 className="text-gray text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            Super Secret Santa
          </h1>
          <div className="container flex flex-col items-center justify-center px-10">
            <h2 className="text-xl tracking-tight">
              Welcome to our web application for creating Secret Santa events!
              With our platform, you can easily organize a gift exchange without
              anyone knowing who they will be buying a gift for until the big
              reveal. Our application ensures that the names of the participants
              are kept secret until the day of the gift exchange, adding an
              element of excitement and surprise to the event. Plus, our
              easy-to-use interface allows you to manage all the details of your
              Secret Santa event, from setting up rules and deadlines to sending
              out invitations and reminders. Get ready to spread some holiday
              cheer with our Secret Santa web application!
            </h2>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
