import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { NavBar } from "../components/NavBar";

import { api } from "../utils/api";

const Santa: NextPage = () => {
  const secretSantas = api.secretSanta.getSecretSantas.useQuery();
  return (
    <>
      <Head>
        <title>Super Secret Santa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-700 text-gray-600">
        {secretSantas && (
          <span>
            {secretSantas.data?.map((ss) => {
              return ss.name;
            })}
          </span>
        )}
      </main>
    </>
  );
};

export default Santa;
