import { NextPage } from "next";
import { useSession } from "next-auth/react";
import dayjs from "dayjs";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { NavBar } from "../../../components/NavBar";
import { api } from "../../../utils/api";

interface SecretSantaProps {
  name: string;
  presentsOpening?: Date | null;
  userId?: string;
}

const EditSecretSanta: NextPage = () => {
  const router = useRouter();
  const { data: sessionData } = useSession();
  const secretSantaMutation = api.secretSanta.updateSecretSanta.useMutation();
  const ss = api.secretSanta.getSecretSantaById.useQuery(
    {
      id: router.query.sid as string,
    },
    {
      enabled:
        sessionData?.user !== undefined && router.query.sid !== undefined,
    }
  );
  return (
    <>
      <Head>
        <title>Super Secret Santa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="flex min-h-screen flex-col items-center bg-gray-700 text-white">
        <div className="justify-top container mt-16 bg-gray-600 py-16 px-10 shadow-lg">
          <div>
            {secretSantaMutation.isSuccess && (
              <div className="text-green-500">Successful updated!</div>
            )}
          </div>
          <form
            className="mt-10 flex flex-wrap"
            onSubmit={(e) => {
              e.preventDefault();
              const formData = new FormData(e.currentTarget);
              const ss = {
                id: router.query.sid as string,
                name: formData.get("name") as string,
                date: new Date(formData.get("presentsOpening") as string),
                participants: [],
              };
            }}
          >
            <div className="flex w-1/2 flex-col">
              <label className="text-2xl font-bold text-white">
                Event Name
              </label>
              <input
                className="mt-2 rounded-md p-2 text-black"
                type="text"
                name="name"
                defaultValue={ss?.data?.name}
              />
            </div>
            <div className="flex w-1/2 flex-col">
              <label className="text-2xl font-bold text-white">
                Date you want to open presents
              </label>
              <input
                className="mt-2 rounded-md p-2 text-black"
                type="date"
                name="presentsOpening"
                defaultValue={dayjs(ss?.data?.presentsOpening).format(
                  "YYYY-MM-DD"
                )}
              />
            </div>
            <div className="flex">
              <button className="form-input mt-5 text-black" type="submit">
                Create
              </button>
              <button
                className="form-input mt-5 text-black"
                type="button"
                onClick={() => router.push("/santa")}
              >
                Back
              </button>
            </div>
          </form>
        </div>
      </main>
    </>
  );
};

export default EditSecretSanta;
