import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import Link from "next/link";

import { api } from "../../../utils/api";
import { NavBar } from "../../../components/NavBar";

const SantaJoin: NextPage = () => {
  const router = useRouter();
  const { data: sessionData } = useSession();
  const sid = router.query.sid as string;

  const secretSanta = api.secretSanta.getSecretSantaById.useQuery(
    {
      id: sid,
    },
    { enabled: sessionData?.user !== undefined }
  );
  return (
    <>
      <Head>
        <title>Super Secret Santa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="flex min-h-screen flex-col items-center bg-gray-700 text-white">
        <div className="justify-top container mt-16 bg-gray-600 py-16 px-10 shadow-lg">
          <h1 className="text-5xl font-bold text-white">
            Want to join this Secret Santa?
          </h1>
        </div>
      </main>
    </>
  );
};

export default SantaJoin;
