import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import Link from "next/link";

import { api } from "../../../utils/api";
import { NavBar } from "../../../components/NavBar";

const SantaJoin: NextPage = () => {
  const router = useRouter();
  const participantMutation =
    api.participant.connectParticipantToUser.useMutation();
  const { data: sessionData } = useSession();
  const sid = router.query.sid as string;

  const secretSanta = api.secretSanta.getSecretSantaById.useQuery({
    id: sid,
  });
  return (
    <>
      <Head>
        <title>Super Secret Santa</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="flex min-h-screen flex-col items-center bg-gray-700 text-white">
        <div className="justify-top container mt-16 bg-gray-600 py-16 px-10 shadow-lg">
          <h1 className="text-5xl font-bold text-white">
            You've been invited to join the {secretSanta?.data?.name} event!
          </h1>

          {sessionData?.user === undefined ? (
            <>
              <h2>
                In order to enable the full functionality of this app, logging
                in is required.
              </h2>
              <Link href="/api/auth/signin">
                <button>Sign in</button>
              </Link>
            </>
          ) : null}

          {sessionData?.user !== undefined ? (
            <>
              <h2 className="text-2xl">Choose which participant you are:</h2>
              <div>
                {secretSanta?.data?.participants?.map((participant) => {
                  return (
                    <div key={participant.id} className="mt-5 bg-gray-400">
                      <span>{participant.name}</span>
                      <button
                        onClick={() => {
                          participantMutation.mutate({
                            id: participant.id,
                            userId: sessionData?.user?.id
                              ? sessionData?.user?.id
                              : "",
                          });

                          router.push(`/connect-done`);
                        }}
                      >
                        Connect
                      </button>
                    </div>
                  );
                })}
              </div>
            </>
          ) : null}
        </div>
      </main>
    </>
  );
};

export default SantaJoin;
