name: CI

on: [push, pull_request]

env:
  SKIP_ENV_VALIDATION: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn
